name: Ecosounds
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
